In [25]:
from textblob import TextBlob
import pprint
import nltk
import pandas as pd
from sklearn import linear_model
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import random
import re
from mpl_toolkits.mplot3d import Axes3D
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import datetime
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
from sklearn.linear_model import SGDRegressor
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from collections import Counter
import math
import strsimpy
from strsimpy.cosine import Cosine

In [26]:
def normalization(df):
    df_min_max_scaled = df.copy() 
  
    for column in df_min_max_scaled.columns: 
        df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())     
    
    return df_min_max_scaled;

In [27]:
df = pd.read_csv("train.csv");
# df = normalization(df);
display(df);

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,1117952,3,3,4,10,4,5,5,7,10,...,7,8,7,2,2,1,4,6,4,0.495
1117953,1117953,2,2,4,3,9,5,8,1,3,...,9,4,4,3,7,4,9,4,5,0.480
1117954,1117954,7,3,9,4,6,5,9,1,3,...,5,5,5,5,6,5,5,2,4,0.485
1117955,1117955,7,3,3,7,5,2,3,4,6,...,6,8,5,3,4,6,7,6,4,0.495
1117956,1117956,4,5,6,9,5,5,2,8,4,...,4,8,6,5,5,6,7,7,8,0.560

In [28]:
train, test = train_test_split(df, test_size=0.3);

train_f = train.drop(columns=['FloodProbability', 'id']);
train_l = train['FloodProbability'];

test_f = test.drop(columns=['FloodProbability', 'id']);
test_l = test['FloodProbability'];

In [29]:
model = linear_model.LinearRegression().fit(train_f, train_l);

In [30]:
print(model.score(test_f, test_l));

0.8461118664053746

In [31]:
input_r = pd.read_csv("test.csv");

ans = pd.DataFrame(model.predict(input_r.drop(columns=['id'])));
ans.to_csv("ans.csv", index=False);